clear;
asus(1) = struct(...
    'brand','asus',...    
    'category','mainstream',...
    'name','Vivobook S510UA',...
    'cpu','Core i3 7100U',...
    'ram','4gb',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','15.6',...
    'res','FHD',...
    'price',12180);
asus(2) = struct(...
    'brand','asus',...
    'category','mainstream',...
    'name','Vivobook S510UA',...
    'cpu','Core i5 7200U',...
    'ram','4gb',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','15.6',...
    'res','FHD',...
    'price',13580);
asus(3) = struct(...
    'brand','asus',...
    'category','mainstream',...
    'name','Vivobook S510UQ',...
    'cpu','Core i5 7200U',...
    'ram','4gb',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce 940MX',...
    'screensize','15.6',...
    'res','FHD',...
    'price',14480);
asus(4) = struct(...
    'brand','asus',...
    'category','ultrabook',...
    'name','Zenbook UX410UA-GV064',...
    'cpu','Core i5 7200U',...
    'ram','4gb',...
    'hdd','500GB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','14',...
    'res','FHD',...
    'price',14950);
asus(5) = struct(...
    'brand','asus',...
    'category','ultrabook',...
    'name','Zenbook UX410UQ-GV066',...
    'cpu','Core i5 7200U',...
    'ram','4gb',...
    'hdd','500GB',...
    'dis_gpu',1,...
    'gpu','Intel HD 620',...
    'screensize','14',...
    'res','FHD',...
    'price',16490);
asus(6) = struct(...
    'brand','asus',...
    'category','ultrabook',...
    'name','Zenbook UX510UX-CN204T',...
    'cpu','Core i7 7500U',...
    'ram','4gb',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX950M',...
    'screensize','15.6',...
    'res','FHD',...
    'price',17890);
asus(7) = struct(...
    'brand','asus',...
    'category','gaming',...
    'name','ASUS GL553VD-FY175',...
    'cpu','Core i5 7300HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1050',...
    'screensize','15.6',...
    'res','FHD',...
    'price',20450);
asus(8) = struct(...
    'brand','asus',...
    'category','gaming',...
    'name','ASUS GL553VD-FY305',...
    'cpu','Core i7 7700HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1050',...
    'screensize','15.6',...
    'res','FHD',...
    'price',21850);
hp(1) = struct(...
    'brand','hp',...
    'category','mainstream',...
    'name','HP Pavilion 14-bf015TU',...
    'cpu','Core i3 7100U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','14',...
    'res','FHD',...
    'price',12290);
hp(2) = struct(...
    'brand','hp',...
    'category','mainstream',...
    'name','HP Pavilion 14-bf018TU ',...
    'cpu','Core i5 7200U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','14',...
    'res','FHD',...
    'price',14290);
hp(3) = struct(...
    'brand','hp',...
    'category','mainstream',...
    'name','HP Pavilion 15-cc018TU ',...
    'cpu','Core i5 7200U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','14',...
    'res','FHD',...
    'price',14790);
hp(4) = struct(...
    'brand','hp',...
    'category','mainstream',...
    'name','HP Pavilion 14-AL115TX ',...
    'cpu','Core i7 7500U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce 940MX',...
    'screensize','14',...
    'res','FHD',...
    'price',16990);
hp(5) = struct(...
    'brand','hp',...
    'category','ultrabook',...
    'name','HP Envy 13-ad075TU',...
    'cpu','Core i5 7200U',...
    'ram','4GB',...
    'hdd','256GB SSD',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','13.3',...
    'res','FHD',...
    'price',20990);
hp(6) = struct(...
    'brand','hp',...
    'category','ultrabook',...
    'name','HP Envy 13-ad074TU',...
    'cpu','Core i7 7500U',...
    'ram','8GB',...
    'hdd','256GB SSD',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','13.3',...
    'res','FHD',...
    'price',25990);
hp(7) = struct(...
    'brand','hp',...
    'category','gaming',...
    'name','HP Omen 15T',...
    'cpu','Core i7 7700HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1050Ti',...
    'screensize','15.6',...
    'res','FHD',...
    'price',25990);
hp(8) = struct(...
    'brand','hp',...
    'category','gaming',...
    'name','HP Omen 17T',...
    'cpu','Core i7 7700HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1060',...
    'screensize','17.3',...
    'res','FHD',...
    'price',31990);
hp(9) = struct(...
    'brand','hp',...
    'category','workstation',...
    'name','HP Zbook 15G3',...
    'cpu','Core i7 6820HQ',...
    'ram','8GB',...
    'hdd','256GB SSD',...
    'dis_gpu',1,...
    'gpu','NVIDIA Quadro M1000M',...
    'screensize','15.6',...
    'res','FHD',...
    'price',26800);
hp(10) = struct(...
    'brand','hp',...
    'category','workstation',...
    'name','HP Zbook Studio G3',...
    'cpu','Xeon 1505M-v5',...
    'ram','16GB',...
    'hdd','256GB SSD',...
    'dis_gpu',1,...
    'gpu','NVIDIA Quadro M1000M',...
    'screensize','15.6',...
    'res','4K',...
    'price',35900);
dell(1) = struct(...
    'brand','dell',...
    'category','mainstream',...
    'name','Dell Inspiron 5567',...
    'cpu','Core i3 7100U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','15.6',...
    'res','HD',...
    'price',11100);
dell(2) = struct(...
    'brand','dell',...
    'category','mainstream',...
    'name','Dell Inspiron 5567',...
    'cpu','Core i5 7200U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','15.6',...
    'res','HD',...
    'price',13590);
dell(3) = struct(...
    'brand','dell',...
    'category','mainstream',...
    'name','Dell Inspiron 5567',...
    'cpu','Core i5 7200U',...
    'ram','4GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','AMD Radeon R7 M445',...
    'screensize','15.6',...
    'res','HD',...
    'price',15900);
dell(4) = struct(...
    'brand','dell',...
    'category','ultrabook',...
    'name','Dell XPS 13',...
    'cpu','Core i5 7200U',...
    'ram','8GB',...
    'hdd','128GB SSD',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','13.3',...
    'res','FHD',...
    'price',23500);
dell(5) = struct(...
    'brand','dell',...
    'category','ultrabook',...
    'name','Dell XPS 13',...
    'cpu','Core i7 7500U',...
    'ram','8GB',...
    'hdd','256GB SSD',...
    'dis_gpu',0,...
    'gpu','Intel HD 620',...
    'screensize','13.3',...
    'res','FHD',...
    'price',29900);
dell(6) = struct(...
    'brand','dell',...
    'category','gaming',...
    'name','Alienware 15R3',...
    'cpu','Core i5 7300HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1060',...
    'screensize','15.6',...
    'res','FHD',...
    'price',35490);
dell(7) = struct(...
    'brand','dell',...
    'category','gaming',...
    'name','Alienware 15R3',...
    'cpu','Core i7 7700HQ',...
    'ram','8GB',...
    'hdd','1TB',...
    'dis_gpu',1,...
    'gpu','NVIDIA Geforce GTX1060',...
    'screensize','15.6',...
    'res','FHD',...
    'price',38900);
dell(8) = struct(...
    'brand','dell',...
    'category','workstation',...
    'name','Dell Precision 7510',...
    'cpu','Core i7 6820HQ',...
    'ram','8GB',...
    'hdd','256GB SSD',...
    'dis_gpu',1,...
    'gpu','NVIDIA Quadro M1000M',...
    'screensize','15.6',...
    'res','FHD',...
    'price',32500);
dell(9) = struct(...
    'brand','dell',...
    'category','workstation',...
    'name','Dell Precision 7510',...
    'cpu','Xeon 1505M v5',...
    'ram','16GB',...
    'hdd','256GB SSD',...
    'dis_gpu',1,...
    'gpu','NVIDIA Quadro M1000M',...
    'screensize','15.6',...
    'res','FHD',...
    'price',39500);
devices_list = [asus hp dell];